export const DB_ANIME_OS = [
  {
    id: 1001,
    category: "serie",
    status: "",
    language: "español",
    title: "Spy x Family",
    season: "Temporada 1",
    information:
      "Todo el mundo tiene una parte de sí mismos que no puede mostrar a los demás. En una era en la que las naciones de todo el mundo se encuentran involucradas en una feroz guerra de información a puerta cerrada, Ostania y Westalis llevan décadas en guerra fría. La División de Inteligencia de Westalis (WISE) envía a su mejor espía, Twilight, en una misión ultrasecreta para vigilar los movimientos de Donovan Desmond, quien dirige el Partido Nacional por la Unidad de Ostania, responsable de bombardear los esfuerzos de paz entre ambos países",
    trailer: "PyjSxCWvq5s",
    background: "wgMxlmsqonV8vymd0JimlUvg82D.jpg",
    poster: "vaIREdPGZOnW9Jrs86mheVVlIQQ.jpg",
  },
  {
    id: 1002,
    category: "serie",
    status: "",
    language: "español",
    title: "Tonikaku Kawaii",
    season: "Temporada 1",
    information:
      "La comedia romántica sigue a un chico llamado Nasa quien conoce a la hermosa chica Tsukasa el día de su ingreso a la preparatoria, e inmediatamente se enamora de ella. Nasa le confiesa sus sentimientos, pero ella le responde que solo saldrá con él si se casan.Años después, cuando Nasa cumple 18 años, Tsukasa aparece de nuevo en su vida solicitándole el prometido matrimonio. Así comenzará su vida de recién casados.",
    trailer: "EYhWTsndKt4",
    background: "rnf2BDKeF1sxPEPhAcdvL0auuxr.jpg",
    poster: "jJKTrIfZKoFV66HGMzSa4tkObK0.jpg",
  },
  {
    id: 1003,
    category: "serie",
    status: "extreme",
    language: "español",
    title: "Kobayashi san Chi no Maid Dragon",
    season: "Temporada 1",
    information:
      "Kobayashi vive sola en un apartamento, hasta que un día, Tooru aparece en su vida y terminan viviendo juntas. Tooru mira con desprecio a los seres humanos, los cuales, percibe como inferiores y simples, pero después de haber sido salvada por Kobayashi, ella hace todo lo posible para devolverle el favor y la ayuda en todo tipo de cosas, aunque no todo va de acuerdo al plan.",
    trailer: "MxMNAo8d17E",
    background: "vc3GVrH46tZPUk7RxRpQO6wH3ny.jpg",
    poster: "jnmL1DoqCYcQH1vGvBvEv4CElnF.jpg",
  },
  {
    id: 1004,
    category: "serie",
    status: "",
    language: "español",
    title: "Zero no Tsukaima",
    season: "Temporada 1",
    information:
      "En un mundo donde existe existe diferencia entre nobles y plebeyos, entre la gente que puede realizar magia y la que no, Louise Françoise Le Blanc de La Vallière, también llamada por sus compañeros en la academia de magia Louise la Zero, debido a que ella no es capaz de realizar algún hechizo sin que haya una explosión. En la academia existe un ritual mediante el cual todos convocan a su Familiar, y Louise convoca a Saito, un humano de la Tierra, siendo un gran alboroto porque nunca se había visto que alguien convocara a un plebeyo",
    trailer: "j-UofYKswhI",
    background: "to2gpUoxeNQlbjfswI8mXldaql0.jpg",
    poster: "lalmkYtSEjPPTWNYrY6a2MWXkvz.jpg",
  },
  {
    id: 1005,
    category: "serie",
    status: "",
    language: "español",
    title: "Re:Zero Empezar de cero en un mundo diferente",
    season: "Temporada 1",
    information:
      "Subaru Natsuki es un estudiante corriente de preparatoria que conoce a una hermosa chica de pelo plateado de otro mundo que lo rescata. Para devolverle el favor decide quedarse con ella, pero el destino con el que carga la muchacha es mucho más pesado de lo que Subaru puede imaginar. Los enemigos atacan sin descanso, uno tras otro, hasta que finalmente mueren tanto él como la chica. Subaru no quiere que la chica resulte herida, con lo que jura acabar con cualquier enemigo, con cualquier destino que le aguarde, siempre por protegerla",
    trailer: "XZiakX-wvnk",
    background: "e0770pcg8ZLR7sWnpiaOz4wlOco.jpg",
    poster: "t3lgcb3RHb2PKyHWf1hU6RQXH6N.jpg",
  },
  {
    id: 1006,
    category: "serie",
    status: "",
    language: "español",
    title: "Kaguya sama wa Kokurasetai",
    season: "Temporada 1",
    information:
      "Kaguya es hija de una familia muy importante y millonaria. Shirogane es también hijo de buena familia y presidente del consejo. Ambos son admirados por todos en la Academia Shuchiin, y ambos están enamorados el uno del otro, pero no se rebajarán a admitirlo y ambos intentan que sea el otro el que declare primero su amor",
    trailer: "rZ95aZmQu_8",
    background: "qKh9R3tsSUA8tuwTlxvhoGz4jYd.jpg",
    poster: "5khbC6AuNgnvnoDbjIMKCOhEtIc.jpg",
  },
  {
    id: 1007,
    category: "serie",
    status: "",
    language: "español",
    title: "Komi-san wa Komyushou Desu",
    season: "Temporada 1",
    information:
      "En un instituto lleno de personajes peculiares, Tadano trata de ayudar a su tímida y asocial compañera de clase Komi a lograr su objetivo: hacerse amiga de 100 personas.",
    trailer: "tLdLTSnmnoA",
    background: "fMBqgWO12D5D7Yj2cKyeRYnKUEV.jpg",
    poster: "hLtPx2WgRGhpoHgrGonSNpkJBmB.jpg",
  },
  {
    id: 1008,
    category: "serie",
    status: "",
    language: "español",
    title: "Kenja no Mago",
    season: "Temporada 1",
    information:
      "Un joven que seguramente había muerto en un accidente, ¡renació en otro mundo cuando era un bebé! Después de eso, fue recogido por el héroe patriota Sage Merlin Wolford y se le dio el nombre de Shin. Fue criado como nieto por Merlín y absorbió las enseñanzas de Merlín, ganándole algunos poderes impactantes; sin embargo, cuando cumplió 15 años, su abuelo Merlín dijo: ¡Olvidé enseñarle sentido común! ¡La vida de fantasía de otro mundo poco convencional de un niño anormal comienza aquí!",
    trailer: "76rrM_R0zdI",
    background: "3sExYAo2rNhKgrHx8S37WMTJHZv.jpg",
    poster: "zlPIFzhr5uvjTmzEU2rjtwazrLX.jpg",
  },
  {
    id: 1009,
    category: "serie",
    status: "",
    language: "español",
    title: "Majo no Tabitabi",
    season: "Temporada 1",
    information:
      "En cierto lugar existe una bruja viajera, de nombre Elaina. Siendo una viajera, ella ha conocido a muchas personas y países mientras continúa con su largo, largo camino.Una ciudad que solo acepta magos, un gigante amante de los músculos, un joven queriendo reencontrarse con su fallecida amada, una princesa abandonada en una destruida ciudad, y la historia de la bruja se entrelazará con todos ellos.Al encontrarse con personas increíblemente extrañas y hacer hermosos recuerdos juntos, ahora, incluso ahora, la bruja no puede evitar que toda su vida siga siendo de encuentros y despedidas.",
    trailer: "nmorW2mif20",
    background: "tT0o4qSrQRhdwl7qyobRzVqh7nE.jpg",
    poster: "z5DovowisN9CKl9JYM0HXtQX1O2.jpg",
  },
  {
    id: 1010,
    category: "serie",
    status: "",
    language: "español",
    title: "Aharen-san wa Hakarenai",
    season: "Temporada 1",
    information:
      "Reina Aharen es una estudiante bajita y callada, a la cuál le es difícil medir la distancia personal entre ella y otras personas, como con su compañero de clase Raidō, que piensa que es muy distante con él.",
    trailer: "8yvgXh9NATE",
    background: "umSMlEN5RIYzlLvSFI2nfme1W02.jpg",
    poster: "aVbzWCkIxIcKmHK4f9aWJueBHNk.jpg",
  },
  {
    id: 1011,
    category: "serie",
    status: "",
    language: "sub-español",
    title: "Chuunibyou Demo Koi Ga Shitai!",
    season: "Temporada 1",
    information:
      "Yuuta Togashi, un chico que solía sufrir de chuu-2 byou y Rikka Takanashi, que todavía tiene el síndrome, formarán un vínculo verdadero entre ambos, es decir, que comenzarán a salir. Se encuentran disfrutando de la vida, o al menos deberían. Sin embargo, Satone Shichimiya, o Sophia Ring SP Saturn VII como le gusta que la llamen, una amiga de Togashi y que sufre del chuu-2 byou como nadie, aparece de repente y pone patas arriba la vida del muchacho. Así comenzará la batalla entre Saturn y Jaou Shingan.",
    trailer: "USgrD2Dqsa0",
    background: "hbLa7NJD9iYodV01phJ6suxty6x.jpg",
    poster: "1IapEqydEiGO0gCgBPVexTFbUCS.jpg",
  },
  {
    id: 1012,
    category: "serie",
    status: "",
    language: "sub-español",
    title: "Date a Live",
    season: "Temporada 1",
    information:
      "Hace treinta años, un extraño fenómeno llamado Terremoto Espacial devastó el centro de Eurasia, llevándose consigo la vida de más de 150 millones de personas. Desde entonces, menores terremotos espaciales se han ido manifestando alrededor del mundo. Shidou Itsuka, un estudiante de secundaria aparentemente normal se encuentra con una chica en el epicentro de un terremoto espacial y es informado por su hermana Kotori que esta chica es uno de los espíritus que, al hacer acto de presencia en el mundo, son causantes de dichos terremotos espaciales. También se entera de que su hermana es la capitana de la nave Ratatoskr y quien lo recluta con el fin de hacer uso de su misteriosa habilidad para sellar los poderes de los espíritus y evitar que se vuelvan una amenaza para la humanidad. Sin embargo, hay un inconveniente: para sellar los poderes de un Espíritu, Shido deberá hacer que éste se enamore de él.",
    trailer: "J7iiWTeC8pk",
    background: "yodTXUp57O9359rsZuRmZMVrgXj.jpg",
    poster: "qi98miuMe1oB5WWo2lonuKFTq4P.jpg",
  },
  {
    id: 1013,
    category: "serie",
    status: "",
    language: "español",
    title: "Kono Subarashii Sekai ni Shukufuku wo",
    season: "Temporada 1",
    information:
      "La vida del amante de los videojuegos, Satou Kazuma, termina cuando es arrollado por un camión. En un inesperado giro del destino reencarna en otro mundo gracias a la diosa Aqua, a una torpe hechicera llamada Megumin y a una delirante caballero llamada Darkness. En esta película este peculiar grupo se enfrentará a una increíble amenaza. ¿Podrán salvar la Villa Carmesí? ¿Qué pasará con Kazuma?",
    trailer: "D0bUJCPEduQ",
    background: "bGKFAQsxS0dzRYSvyspRm0rZlfo.jpg",
    poster: "oRaOeQlwktbGSd2T31FYAcgHZlh.jpg",
  },
  {
    id: 1014,
    category: "movie",
    status: "",
    language: "español",
    title: "En el bosque de la luz de las luciérnagas",
    information:
      "Cuando era pequeña, Hotaru se perdió en el bosque cerca del lugar donde va todos los veranos, la casa de su tío. Allí tuvo un extraño encuentro con Gin que la ayuda a encontrar el camino de vuelta. Gin es un joven que lleva una máscara blanca y que, debido a un hechizo, no puede ser tocado por ningún humano. Ella empieza a visitarlo todos los veranos según va creciendo, mientras espera la llegada del verano, para que su tiempo juntos continúe.",
    trailer: "VRvtWoI2RCU",
    background: "hAHF7nzJHUKwrhyl3nB5ckSLHuc.jpg",
    poster: "xE763r1dnYji0gOxrSxBtzyouSf.jpg",
  },
  {
    id: 1015,
    category: "movie",
    status: "",
    language: "español",
    title: "Los Tipos Malos",
    information:
      "Cinco villanos notorios: el Sr. Wolf, Mr. Snake, Mr. Piranha, Mr. Shark y Ms. Tarantula, que han pasado toda una vida juntos realizando grandes atracos.",
    trailer: "qyYvtl6mttc",
    background: "fEe5fe82qHzjO4yej0o79etqsWV.jpg",
    poster: "wFdwJh3fbhp5aiRbQelVz1mbbwP.jpg",
  },
  {
    id: 1016,
    category: "movie",
    status: "",
    language: "español",
    title: "Red",
    information:
      "Mei Lee, una niña de 13 años un poco rara pero segura de sí misma, se debate entre ser la hija obediente que su madre quiere que sea y el caos propio de la adolescencia. Ming, su protectora y ligeramente exigente madre, no se separa nunca de ella lo que es una situación poco deseable para una adolescente. Y por si los cambios en su vida y en su cuerpo no fueran suficientes, cada vez que se emociona demasiado (lo que le ocurre prácticamente todo el tiempo), se convierte en un panda rojo gigante.",
    trailer: "upGoAejd7LM",
    background: "fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    poster: "hUupIkIKPpNLYniPGRxRpEQFrX3.jpg",
  },
  {
    id: 1017,
    category: "movie",
    status: "",
    language: "español",
    title: "Los Siete Pecados Capitales: La maldición de la luz",
    information:
      "Con la ayuda del Dragón Sin of Wrath Meliodas y los peores rebeldes de la historia, los Siete Pecados Capitales, la Guerra Santa, en la que cuatro razas, incluyendo Humanos, Diosas, Hadas y Gigantes lucharon contra los Demonios, finalmente se sobre. A costa de la vida de Escanor El pecado del orgullo del león, el Rey Demonio fue derrotado y el mundo recuperó la paz. Después de eso, cada uno de los pecados toma su propio camino.",
    trailer: "6ribjsdOeM8",
    background: "Aoueuf0P1U9oqf4dgN6dqxl7hsE.jpg",
    poster: "k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg",
  },
  {
    id: 1018,
    category: "serie",
    status: "extreme",
    language: "sub-español",
    title: "Las Quintillizas",
    information:
      "Fuutarou Uesugi es un estudiante de segundo año de preparatoria/instituto cuya familia siempre ha sido muy pobre. Un día recibe una suculenta oferta de trabajo como tutor a medio tiempo... ¡pero sus estudiantes resultan ser unas chicas de su propia clase! Para complicar más las cosas, son quintillizas... Las cinco hermanas son todas muy atractivas, pero no es lo único que tienen en común: todas odian estudiar y sus calificaciones siempre están al límite de la catástrofe. Tendrá que conseguir que las cinco estudien, pero primero tendrá que estudiar él cómo ganarse su confianza.",
    trailer: "cYhQRTmU0aA",
    background: "dwEkNoGFZJWqiwJrnzVfmtmVhfU.jpg",
    poster: "zIBfMBcV7ENjEfuFx93xJYnOtLs.jpg",
  },
  {
    id: 1019,
    category: "serie",
    status: "",
    language: "español",
    title: "Kawaii dake ja Nai Shikimori-san",
    season: "Temporada 1",
    information:
      "Shikimori parece ser la novia perfecta, sin embargo, tiene un lado bastante oscuro que solo surge bajo ciertas circunstancias. ¡Y su novio Izumi adora estar con ella cuando esto ocurre!",
    trailer: "ejBIT5AFDhQ",
    background: "9q69OEoEtpb7NcSZwNFZzF29o0E.jpg",
    poster: "xevZrwMuqJsrd7kiBsCBzc2ZWY.jpg",
  },
  {
    id: 1020,
    category: "serie",
    status: "",
    language: "español",
    title: "My Dress-Up Darling",
    season: "Temporada 1",
    information:
      "¡Dos mundos opuestos chocan cuando un chico tímido y una chica muy popular encuentran un punto de encuentro gracias al cosplay!",
    trailer: "UvIIy7EEfUk",
    background: "sHvkvaUHTob1jHbF6LxjR3q3GPe.jpg",
    poster: "A6mxBwvvv63JXZm3xXKv4SugE0L.jpg",
  },
  {
    id: 1021,
    category: "serie",
    status: "",
    language: "sub-español",
    title: "Komi-san wa Komyushou Desu",
    season: "Temporada 1",
    information:
      "En un instituto lleno de personajes peculiares, Tadano trata de ayudar a su tímida y asocial compañera de clase Komi a lograr su objetivo: hacerse amiga de 100 personas.",
    trailer: "tLdLTSnmnoA",
    background: "fMBqgWO12D5D7Yj2cKyeRYnKUEV.jpg",
    poster: "hLtPx2WgRGhpoHgrGonSNpkJBmB.jpg",
  },
  {
    id: 1022,
    category: "serie",
    status: "",
    language: "español",
    title: "Sword Art Online",
    season: "Temporada 1",
    information:
      "Escapar es imposible hasta terminar el juego; un game over significaría una verdadera muerte. Sin saber la verdad de la siguiente generación del Multijugador Masivo Online, 'Sword Art Online(SAO)', con 10 mil usuarios unidos juntos abriendo las cortinas para esta cruel batalla a muerte. Participando solo en SAO, el protagonista Kirito ha aceptado inmediatamente la verdad de este MMO. Y, en el mundo del juego, un gigante castillo flotante llamado 'Aincrad', Kirito se distinguió a si mismo como un jugador solitario. Apuntando a terminar el juego al alcanzar la planta mas alta el solo continua avanzando arriesgadamente hasta que recibe una invitación a la fuerza de una guerrera y esgrimista experta, Asuna, con la cual tendrá que hacer equipo.",
    trailer: "6ohYYtxfDCg",
    background: "eNWWEY4HyaHK6ypwZI3yqkf4Osf.jpg",
    poster: "hL8UP5Cj04ywytJiYiRHMTdhhCC.jpg",
  },
  {
    id: 1023,
    category: "serie",
    status: "",
    language: "español",
    title: "Kimetsu No Yaiba",
    season: "Temporada 1",
    information:
      "Desde la antigüedad, abundaban los rumores sobre demonios devoradores de hombres que acechaban en el bosque. Debido a esto, los pobladores locales nunca se aventuran afuera por la noche. La leyenda dice que un asesino de demonios también vaga por la noche, persiguiendo a estos demonios sedientos de sangre. Para el joven Tanjirou, estos rumores pronto se convertirán en su dura realidad ... Desde la muerte de su padre, Tanjirou se ha comprometido a apoyar a su familia. Aunque sus vidas pueden ser endurecidas por la tragedia, han encontrado la felicidad. Pero ese calor efímero se destruye un día cuando Tanjirou encuentra a su familia asesinada y el único sobreviviente, su hermana Nezuko, se convirtió en un demonio. Sin embargo, para su sorpresa, Nezuko aún muestra signos de emoción humana y pensamiento ... Así comienza la búsqueda de Tanjirou para luchar contra los demonios y hacer que su hermana vuelva a ser humana.",
    trailer: "VQGCKyvzIM4",
    background: "iBAtBLqCMON3NPIjyQ1wdMbpTAk.jpg",
    poster: "uspk5k68Hamd86oCgLoUQ1s6SuW.jpg",
  },
  {
    id: 1024,
    category: "serie",
    status: "",
    language: "sub-español",
    title: "Murenase! Seton Gakuen",
    season: "Temporada 1",
    information:
      "La historia tiene lugar en una escuela para animales, cuyo plan de estudio principal se basa en la idea de la “supervivencia del más apto”. En dicha escuela va también un humano, que odia a los animales y una solitaria chica lobo, cuando se conocen, comienzan de verdad su vida estudiantil.",
    trailer: "JlCLXa-pHZc",
    background: "iJWopnlQYvVVRG9rKpQnhYM3dsO.jpg",
    poster: "yXSH5BYOhYt26S5x7Aqz2VXj6P1.jpg",
  },
  {
    id: 1025,
    category: "serie",
    status: "",
    language: "sub-español",
    title: "Amagi Brilliant Park",
    season: "Temporada 1",
    information:
      "La serie da comienzo con Seiya Kanie, un chico de instituto que es invitado a una cita a un parque de atracciones por parte de una preciosa y misteriosa nueva estudiante transferida llamada Isuzu Sento. Allí le presentan a Ratifa, una princesa real y mánager del parque, donde le piden que gestione ese decepcionante parque de atracciones en las afueras de Tokio.",
    trailer: "wISkNzP2htM",
    background: "qFVgiQGEZZyuteb3eQUnTTww6u9.jpg",
    poster: "menCOx2SGRg3cHAfEHOeJIXG9RL.jpg",
  },
  // {
  //   id: 1050,
  //   category: "",
  //   status: "",
  //   language: "",
  //   title: "",
  //   season: "",
  //   information: "",
  //   trailer: "",
  //   background: "",
  //   poster: "",
  //   episodes: [{ id: 1, src: "" }],
  // },
];


//data para la pagina AnimeOs
export function getItems() {
  return DB_ANIME_OS;
}

export function getItem(id) {
  return DB_ANIME_OS.find((DB_ITEM) => DB_ITEM.id === id);
}
